theme = "dracula"
icons = "awesome"

[[block]]
block = "kdeconnect"
format = "{name} {bat_icon}  {notif_icon}{notif_count}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average} avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

# [[block]]
# block = "nvidia_gpu"
# label = "GPU"
# show_memory = false
# show_clocks = false
# interval = 1

[[block]]
block = "sound"
format = "{output_description} {volume}"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

