idle_bg = "#5e3535"
idle_fg = "#ffffff"
info_bg = "#f64646"
info_fg = "#ffffff"
good_bg = "#4c784b"
good_fg = "#ffffff"
warning_bg = "#8d2828"
warning_fg = "#ffffff"
critical_bg = "#be0b0b"
critical_fg = "#ffffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
